apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod3
spec:
  selector:
    matchLabels:
      app: pod3
  template:
    metadata:
      labels:
        app: pod3
    spec:
      containers:
      - name: pod3-container
        image: nginx
        ports:
        - containerPort: 80
